name: salah
description: "Namaz vakitlerini gösteren bir uygulama."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1  # Semantic Versioning: MAJOR.MINOR.PATCH+buildNumber

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  intl: ^0.19.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/salah_app_icon_black.png
